### PR TITLE
chore: remove circleci config

### PR DESCRIPTION
**Pull request by SgtPooki**
### Other things to do

- [ ] Update readme to talk about how site is hosted on fleek now (permissioned link: https://app.fleek.co/#/sites/multiformatsio/overview)
- [x] remove circleci integration in settings
- [ ] Ensure DNSLink for multiformats.io is removed?

related to https://github.com/protocol/infra/issues/1202

### CODE REVIEW

**Comment by galargh** [comment]
I'll be able to take care of disabling CircleCI for this repo.

**Review by rvagg — APPROVED** [review]

**Comment by galargh** [comment]
> I'll be able to take care of disabling CircleCI for this repo.

CircleCI is now disabled for this repo.

**Comment by SgtPooki** [comment]
FYI future instructions for migrating sites from ipfs-cluster to fleek are at https://github.com/protocol/infra/issues/1202#issuecomment-1613459690

**Comment by SgtPooki** [comment]
@galargh @rvagg opened https://github.com/multiformats/website/pull/74 to finish up the tasks from this

**Pull request merged**
