### PR TITLE
Update config for current iteration

### PR DESCRIPTION
**Pull request by gsf**
This should fix the stylesheet hrefs, etc. Do these config values and the README link need to be updated with every commit? Should they point at http://multiformats.io or an ipns URL instead?

### CODE REVIEW

**Comment by gsf** [comment]
This is following up on #6.

**Comment by VictorBjelkholm** [comment]
I'm not sure why the hash of the site is in the configuration, we should be using relative links so it doesn't matter where the site lives. Maybe @RichardLitt knows more about why

**Comment by diasdavid** [comment]
It's because of jekyll, relative links don't play well when using DNSLink and loading from hash at the same time.

For more notes, see: https://github.com/ipfs/notes/issues/66

**Comment by RichardLitt** [comment]
@diasdavid is right. If we can find a way to not include a hash, it would be better; I wasn't able to find one for Jekyll. I'd suggest porting the whole thing over to Hugo.

**Comment by VictorBjelkholm** [comment]
@diasdavid @RichardLitt this shouldn't be any problem. I need to dig deeper but what I've done in the past when it comes to build static websites to works anywhere, is to link to the page, coming from above.

I made a example here: Qmb7SBnCG2buyEM5ZkFtSwXwYxCtwJVWFf6tSEJg31ud7n

This website works no matter where you are visiting it.

**Comment by RichardLitt** [comment]
That hash isn't resolving: did you pin it?

**Comment by gsf** [comment]
http://multiformats.io doesn't load because the stylesheets aren't resolving. Hence this patch.

**Comment by VictorBjelkholm** [comment]
@RichardLitt should be working, try again.

**Comment by RichardLitt** [comment]
You sure? Tried to run it locally, got this:

```
15:45:43.722 ERROR core/serve: Path Resolve error: Failed to get block for QmWsdJDWoKKohR8FaxRRZgovKpfFfQ7KfKkbFL92geeNoa: context canceled gateway_handler.go:509
15:45:57.845 ERROR core/serve: Path Resolve error: Failed to get block for QmWsdJDWoKKohR8FaxRRZgovKpfFfQ7KfKkbFL92geeNoa: context canceled gateway_handler.go:509
```

**Comment by RichardLitt** [comment]
Nevermind, seems to work. How did you generate this?

**Comment by VictorBjelkholm** [comment]
@RichardLitt this was manually written for the purpose of this example. Depends on the theme and how the links are written. I'll implement it for the websites though, and give you a shout when I have something to show :)

**Comment by VictorBjelkholm** [comment]
This is not needed anymore as we're using hugo now.

**Pull request closed without merging**
