### PR TITLE
Improved multiaddr documentation

### PR DESCRIPTION
**Pull request by acul71**
Expanded the TODO sections with examples

### CODE REVIEW

**Review by dhuseby — APPROVED** [review]
LGTM. Thanks @acul71!! Thanks PLDG.

**Comment by rvagg** [comment]
nice, unfortunately I don't think anyone with push access watches this repo anymore, list needs updating (I started on it but gave up out of exhaustion just thinking how out of date all of this is): https://github.com/multiformats/github-mgmt/blob/master/github/multiformats.yml

**Comment by jessicaschilling** [comment]
@rvagg I inexplicably can still merge - haven’t been following a thing but mention me if you need.

**Comment by rvagg** [comment]
@jessicaschilling (thanks) **_ping_**, since this has @dhuseby's :heavy_check_mark: this can be merged.

**Comment by jessicaschilling** [comment]
Merging per @rvagg. Note I’m no longer an active maintainer, just happened to see the notification - thanks.

**Comment by bumblefudge** [comment]
Whoops just saw this.  Thanks again @acul71  and @dhuseby !

**Comment by dhuseby** [comment]
🚀

**Pull request merged**
